name: Run rubocop

on:
  push:
    branches:
      - feature/**
      - hotfix/**
  pull_request:
    branches:
      - feature/**
      - hotfix/**

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./api

      - name: Install Dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle lock --add-platform x86_64-linux
          bundle install --jobs=4 --retry=3 --path=vendor/bundle

      - name: Check Ruby version
        run: ruby --version

      - name: Run RuboCop
        if: ${{ github.event_name == 'pull_request' }}
        run: bundle exec rubocop --only-changed

      - name: Run RuboCop on changed files
        if: ${{ github.event_name == 'push' }}
        run: bundle exec rubocop --only-changed
