name: Run rubocop

on:
  push:
    branches:
      - feature/**
      - hotfix/**
  pull_request:
    branches:
      - feature/**
      - hotfix/**

jobs:
  rubocop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1.1

      - name: Run bundle install & Run RuboCop
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd api
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop --only-changed

      - name: Run RuboCop on changed files
        if: ${{ github.event_name == 'push' }}
        run: |
          cd api
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop --only-changed
