name: Run rubocop

on:
  push:
    branches:
      - feature/**
      - hotfix/**
  pull_request:
    branches:
      - feature/**
      - hotfix/**

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./api
          gem-cache: true

      - name: Check Ruby version
        run: ruby --version

      - name: Run rubocop
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            bundle exec rubocop
          elif [ "${{ github.event_name }}" = "push" ]; then
            git diff --name-only HEAD^ HEAD | grep '.rb$' | xargs bundle exec rubocop -a --force-exclusion
          fi
